import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Audiowide, Carattere } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import { MessageSquareText } from "lucide-react"; // Import MessageSquareText

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const audiowide = Audiowide({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-audiowide",
});

const carattere = Carattere({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-carattere",
});

export const metadata: Metadata = {
  title: "Lucky HomeStay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const whatsappNumber = "94777237120"; // International format without '+'
  const whatsappMessage = encodeURIComponent("Hello, I'd like to inquire about a booking.");
  const whatsappLink = `https://wa.me/${whatsappNumber}?text=${whatsappMessage}`;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${audiowide.variable} ${carattere.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />

        {/* WhatsApp FAB */}
        <a
          href={whatsappLink}
          target="_blank"
          rel="noopener noreferrer"
          className="fixed bottom-6 right-6 bg-green-500 hover:bg-green-600 text-white p-4 rounded-full shadow-lg flex items-center justify-center z-50 transition-colors duration-300"
          aria-label="WhatsApp Us"
        >
          <MessageSquareText className="h-7 w-7" />
        </a>
      </body>
    </html>
  );
}
